
import turtle
turtle.title("Turtle Example")


t = turtle.Turtle()
t.shape("turtle")

# draw indonesia flag
# t.fillcolor('red')

# t.begin_fill()
# t.up()
# t.right(180)
# t.forward(100)
# t.right(90)
# t.forward(180)
# t.fillcolor('red')

# t.begin_fill()
# t.down()
# t.right(90)
# t.forward(180)
# t.right(90)
# t.forward(90)
# t.right(90)
# t.forward(180)
# t.right(90)
# t.forward(90)
# t.end_fill()
# t.fillcolor('white')
# t.begin_fill
# t.up()
# t.right(180)
# t.forward(90)
# t.down()
# t.forward(90)
# t.left(90)
# t.forward(180)
# t.left(90)
# t.forward(90)
# t.left(90)
# t.forward(180)
# t.end_fill()
# draw vietnam flag
# t.fillcolor('red')
# t.begin_fill()
# t.up()
# t.right(180)
# t.forward(90)
# t.right(90)
# t.forward(180)
# t.right(90)
# t.forward(280)
# t.right(90)
# t.forward(180)
# t.right(90)
# t.forward(90)
# t.end_fill()

# t.right(90)
# t.forward(90)
# t.fillcolor('yellow')
# t.begin_fill()
# t.right(90)

# t.left(180)



# for i in range(5):
#     t.right(180-36)
#     t.forward(90)

# t.end_fill()

# draw korea flag
t.speed(0)
r = 90
d = 360
horisonalspace=5
diaganalspace=30
t.left(90)
t.up()
t.fillcolor('red')
t.begin_fill()
t.circle(r,d)
t.end_fill()
# size = r/2 # Change to whatever size you want, but as a negative number
# degrees = -180 # Change degrees to match half a circle, HINT 360/2
t.fillcolor('blue')
t.begin_fill()
t.circle(r/2,d/2)
size = -(r/2) # Change to whatever size you want, but as a negative number
degrees = 180 # Change degrees to match half a circle, HINT 360/2
t.circle(size,degrees)
t.circle(-r,-d/2)
t.end_fill()
t.left(90)
t.forward(100)
t.left(90)
t.forward(50)
t.left(45)
t.fillcolor('black')
t.begin_fill()
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.forward(30)
t.right(90)
t.forward(5)
t.end_fill()
t.right(90)
t.forward(40)
t.begin_fill()
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.forward(30)
t.right(90)
t.forward(5)
t.end_fill()
t.forward(10)
t.left(90)
t.forward(40)
t.left(180)
t.begin_fill()
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.forward(40)
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.forward(40)
t.right(90)
t.forward(5)
t.end_fill()
t.forward(10)
t.left(90)
t.forward(30)
t.left(180)
t.begin_fill()
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.forward(30)
t.right(90)
t.forward(5)
t.end_fill()
t.right(90)
t.forward(40)
t.begin_fill()
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.forward(30)
t.right(90)
t.forward(5)
t.end_fill()
t.left(90)
t.forward(30)
t.right(45)
t.forward(100)
t.right(45)
t.begin_fill()
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.forward(30)
t.right(90)
t.forward(5)
t.end_fill()
t.right(90)
t.forward(40)
t.begin_fill()
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.forward(30)
t.right(90)
t.forward(5)
t.end_fill()
t.forward(10)
t.left(90)
t.forward(40)
t.right(180)
t.begin_fill()
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.forward(30)
t.right(90)
t.forward(5)
t.end_fill()
t.right(90)
t.forward(40)
t.begin_fill()
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.forward(30)
t.right(90)
t.forward(5)
t.end_fill()
t.forward(10)
t.left(90)
t.forward(40)
t.right(180)
t.begin_fill()
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.forward(30)
t.right(90)
t.forward(5)
t.end_fill()
t.right(90)
t.forward(40)
t.begin_fill()
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.forward(30)
t.right(90)
t.forward(5)
t.end_fill()
t.right(180)
t.forward(horisonalspace*3+5*2)
t.right(90)
t.forward(10+diaganalspace)
t.left(45)
t.forward(50)
t.left(90)
t.forward(100+r*2+100)
t.left(90)
t.forward(50)
t.left(45)
t.begin_fill()
t.forward(diaganalspace+5+diaganalspace)
t.left(90)
t.forward(horisonalspace)
t.left(90)
t.forward(diaganalspace+5+diaganalspace)
t.left(90)
t.forward(horisonalspace)
t.end_fill()
t.right(180)
t.forward(10+horisonalspace)
t.right(90)
t.begin_fill()
t.forward(diaganalspace)
t.right(90)
t.forward(horisonalspace)
t.right(90)
t.forward(diaganalspace)
t.right(90)
t.forward(horisonalspace)
t.right(90)
t.end_fill()
t.forward(diaganalspace+horisonalspace)
t.begin_fill()
t.forward(diaganalspace)
t.right(90)
t.forward(horisonalspace)
t.right(90)
t.forward(30)
t.right(90)
t.forward(5)
t.right(90)
t.end_fill()
t.right(180)
t.forward(10)
t.right(90)
t.forward(horisonalspace)
t.begin_fill()
t.right(90)
t.forward(40)
t.left(90)
t.forward(5)
t.left(90)
t.forward(70)
t.left(90)
t.forward(5)
t.left(90)
t.forward(50)
t.end_fill()
t.right(90)
t.forward(15+30)
t.right(90)
t.forward(40)
t.right(45)
t.forward(130)
t.right(45)
t.begin_fill()
t.forward(70)
t.right(90)
t.forward(5)
t.right(90)
t.forward(70)
t.right(90)
t.forward(5)
t.end_fill()
t.right(180)
t.forward(10)
t.left(90)
t.begin_fill()
t.forward(70)
t.right(90)
t.forward(5)
t.right(90)
t.forward(70)
t.right(90)
t.forward(5)
t.end_fill()
t.right(180)
t.forward(10)
t.left(90)
t.begin_fill()
t.forward(70)
t.right(90)
t.forward(5)
t.right(90)
t.forward(70)
t.right(90)
t.forward(5)
t.end_fill()


#Draw Cher Flag XD

# w = 200
# r=(w/4)
# d= 360
# t.up()

# t.fillcolor('green')
# t.begin_fill()
# for i in range(4):
#     t.forward(w)
#     t.left(90)

# t.end_fill() 
# t.fillcolor('white')
# t.begin_fill()
# t.forward(3*w/4)
# t.left(90)
# t.forward(w/3)
# t.begin_fill()
# t.right(45)
# t.circle(r,d)
# t.end_fill()
# t.forward(20)
# t.fillcolor('green')
# t.begin_fill()
# t.circle(r,d)
# t.end_fill()
turtle.Screen().exitonclick()